# -*- coding: utf-8 -*-

"""
    thingspaceconnectivitymanagementapilib.models.add_devices_response_message
 
    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/05/2016
"""
from .device_id import DeviceId
from .base_model import BaseModel

class AddDevicesResponseMessage(BaseModel):

    """Implementation of the 'AddDevicesResponseMessage' model.

    TODO: type model description here.

    Attributes:
        device_ids (list of DeviceId): TODO: type description here.
        response (string): TODO: type description here.

    """

    def __init__(self, 
                 device_ids = None,
                 response = None):
        """Constructor for the AddDevicesResponseMessage class"""
        
        # Initialize members of the class
        self.device_ids = device_ids
        self.response = response

        # Create a mapping from Model property names to API property names
        self.names = {
            "device_ids" : "deviceIds",
            "response" : "response",
        }


    @classmethod
    def from_dictionary(cls, 
                        dictionary):
        """Creates an instance of this model from a dictionary
       
        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.
            
        Returns:
            object: An instance of this structure class.
            
        """
        if dictionary == None:
            return None
        else:
            # Extract variables from the dictionary
            device_ids = None
            if dictionary.get("deviceIds") != None:
                device_ids = list()
                for structure in dictionary.get("deviceIds"):
                    device_ids.append(DeviceId.from_dictionary(structure))
            response = dictionary.get("response")
            # Return an object of this model
            return cls(device_ids,
                       response)
