# -*- coding: utf-8 -*-

"""
    thingspaceconnectivitymanagementapilib.models.callback_action_response
 
    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/05/2016
"""
from .base_model import BaseModel

class CallbackActionResponse(BaseModel):

    """Implementation of the 'CallbackActionResponse' model.

    TODO: type model description here.

    Attributes:
        account_name (string): TODO: type description here.
        service_name (string): TODO: type description here.

    """

    def __init__(self, 
                 account_name = None,
                 service_name = None):
        """Constructor for the CallbackActionResponse class"""
        
        # Initialize members of the class
        self.account_name = account_name
        self.service_name = service_name

        # Create a mapping from Model property names to API property names
        self.names = {
            "account_name" : "accountName",
            "service_name" : "serviceName",
        }


    @classmethod
    def from_dictionary(cls, 
                        dictionary):
        """Creates an instance of this model from a dictionary
       
        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.
            
        Returns:
            object: An instance of this structure class.
            
        """
        if dictionary == None:
            return None
        else:
            # Extract variables from the dictionary
            account_name = dictionary.get("accountName")
            service_name = dictionary.get("serviceName")
            # Return an object of this model
            return cls(account_name,
                       service_name)
