# -*- coding: utf-8 -*-

"""
    thingspaceconnectivitymanagementapilib.models.create_dev_group_request
 
    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/05/2016
"""
from .device_id import DeviceId
from .base_model import BaseModel

class CreateDevGroupRequest(BaseModel):

    """Implementation of the 'CreateDevGroupRequest' model.

    TODO: type model description here.

    Attributes:
        account_name (string): TODO: type description here.
        devices_to_add (list of DeviceId): TODO: type description here.
        group_description (string): TODO: type description here.
        group_name (string): TODO: type description here.

    """

    def __init__(self, 
                 account_name = None,
                 devices_to_add = None,
                 group_description = None,
                 group_name = None):
        """Constructor for the CreateDevGroupRequest class"""
        
        # Initialize members of the class
        self.account_name = account_name
        self.devices_to_add = devices_to_add
        self.group_description = group_description
        self.group_name = group_name

        # Create a mapping from Model property names to API property names
        self.names = {
            "account_name" : "accountName",
            "devices_to_add" : "devicesToAdd",
            "group_description" : "groupDescription",
            "group_name" : "groupName",
        }


    @classmethod
    def from_dictionary(cls, 
                        dictionary):
        """Creates an instance of this model from a dictionary
       
        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.
            
        Returns:
            object: An instance of this structure class.
            
        """
        if dictionary == None:
            return None
        else:
            # Extract variables from the dictionary
            account_name = dictionary.get("accountName")
            devices_to_add = None
            if dictionary.get("devicesToAdd") != None:
                devices_to_add = list()
                for structure in dictionary.get("devicesToAdd"):
                    devices_to_add.append(DeviceId.from_dictionary(structure))
            group_description = dictionary.get("groupDescription")
            group_name = dictionary.get("groupName")
            # Return an object of this model
            return cls(account_name,
                       devices_to_add,
                       group_description,
                       group_name)
