# -*- coding: utf-8 -*-

"""
    thingspaceconnectivitymanagementapilib.models.device_list_response
 
    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/05/2016
"""
from .device import Device
from .base_model import BaseModel

class DeviceListResponse(BaseModel):

    """Implementation of the 'DeviceListResponse' model.

    TODO: type model description here.

    Attributes:
        devices (list of Device): TODO: type description here.
        has_more_data (bool): TODO: type description here.

    """

    def __init__(self, 
                 devices = None,
                 has_more_data = None):
        """Constructor for the DeviceListResponse class"""
        
        # Initialize members of the class
        self.devices = devices
        self.has_more_data = has_more_data

        # Create a mapping from Model property names to API property names
        self.names = {
            "devices" : "devices",
            "has_more_data" : "hasMoreData",
        }


    @classmethod
    def from_dictionary(cls, 
                        dictionary):
        """Creates an instance of this model from a dictionary
       
        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.
            
        Returns:
            object: An instance of this structure class.
            
        """
        if dictionary == None:
            return None
        else:
            # Extract variables from the dictionary
            devices = None
            if dictionary.get("devices") != None:
                devices = list()
                for structure in dictionary.get("devices"):
                    devices.append(Device.from_dictionary(structure))
            has_more_data = dictionary.get("hasMoreData")
            # Return an object of this model
            return cls(devices,
                       has_more_data)
