# -*- coding: utf-8 -*-

"""
    thingspaceconnectivitymanagementapilib.models.device
 
    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/05/2016
"""
from .carrier_information import CarrierInformation
from .kv_pair import KvPair
from .device_id import DeviceId
from .base_model import BaseModel

class Device(BaseModel):

    """Implementation of the 'Device' model.

    TODO: type model description here.

    Attributes:
        account_name (string): TODO: type description here.
        billing_cycle_end_date (string): TODO: type description here.
        carrier_informations (list of CarrierInformation): TODO: type
            description here.
        connected (bool): TODO: type description here.
        created_at (string): TODO: type description here.
        custom_fields (list of KvPair): TODO: type description here.
        device_ids (list of DeviceId): TODO: type description here.
        extended_attributes (list of KvPair): TODO: type description here.
        group_names (list of string): TODO: type description here.
        ip_address (string): TODO: type description here.
        last_activation_by (string): TODO: type description here.
        last_activation_date (string): TODO: type description here.
        last_connection_date (string): TODO: type description here.

    """

    def __init__(self, 
                 account_name = None,
                 billing_cycle_end_date = None,
                 carrier_informations = None,
                 connected = None,
                 created_at = None,
                 custom_fields = None,
                 device_ids = None,
                 extended_attributes = None,
                 group_names = None,
                 ip_address = None,
                 last_activation_by = None,
                 last_activation_date = None,
                 last_connection_date = None):
        """Constructor for the Device class"""
        
        # Initialize members of the class
        self.account_name = account_name
        self.billing_cycle_end_date = billing_cycle_end_date
        self.carrier_informations = carrier_informations
        self.connected = connected
        self.created_at = created_at
        self.custom_fields = custom_fields
        self.device_ids = device_ids
        self.extended_attributes = extended_attributes
        self.group_names = group_names
        self.ip_address = ip_address
        self.last_activation_by = last_activation_by
        self.last_activation_date = last_activation_date
        self.last_connection_date = last_connection_date

        # Create a mapping from Model property names to API property names
        self.names = {
            "account_name" : "accountName",
            "billing_cycle_end_date" : "billingCycleEndDate",
            "carrier_informations" : "carrierInformations",
            "connected" : "connected",
            "created_at" : "createdAt",
            "custom_fields" : "customFields",
            "device_ids" : "deviceIds",
            "extended_attributes" : "extendedAttributes",
            "group_names" : "groupNames",
            "ip_address" : "ipAddress",
            "last_activation_by" : "lastActivationBy",
            "last_activation_date" : "lastActivationDate",
            "last_connection_date" : "lastConnectionDate",
        }


    @classmethod
    def from_dictionary(cls, 
                        dictionary):
        """Creates an instance of this model from a dictionary
       
        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.
            
        Returns:
            object: An instance of this structure class.
            
        """
        if dictionary == None:
            return None
        else:
            # Extract variables from the dictionary
            account_name = dictionary.get("accountName")
            billing_cycle_end_date = dictionary.get("billingCycleEndDate")
            carrier_informations = None
            if dictionary.get("carrierInformations") != None:
                carrier_informations = list()
                for structure in dictionary.get("carrierInformations"):
                    carrier_informations.append(CarrierInformation.from_dictionary(structure))
            connected = dictionary.get("connected")
            created_at = dictionary.get("createdAt")
            custom_fields = None
            if dictionary.get("customFields") != None:
                custom_fields = list()
                for structure in dictionary.get("customFields"):
                    custom_fields.append(KvPair.from_dictionary(structure))
            device_ids = None
            if dictionary.get("deviceIds") != None:
                device_ids = list()
                for structure in dictionary.get("deviceIds"):
                    device_ids.append(DeviceId.from_dictionary(structure))
            extended_attributes = None
            if dictionary.get("extendedAttributes") != None:
                extended_attributes = list()
                for structure in dictionary.get("extendedAttributes"):
                    extended_attributes.append(KvPair.from_dictionary(structure))
            group_names = dictionary.get("groupNames")
            ip_address = dictionary.get("ipAddress")
            last_activation_by = dictionary.get("lastActivationBy")
            last_activation_date = dictionary.get("lastActivationDate")
            last_connection_date = dictionary.get("lastConnectionDate")
            # Return an object of this model
            return cls(account_name,
                       billing_cycle_end_date,
                       carrier_informations,
                       connected,
                       created_at,
                       custom_fields,
                       device_ids,
                       extended_attributes,
                       group_names,
                       ip_address,
                       last_activation_by,
                       last_activation_date,
                       last_connection_date)
