# -*- coding: utf-8 -*-

"""
    thingspaceconnectivitymanagementapilib.models.device_id
 
    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/05/2016
"""
from .base_model import BaseModel

class DeviceId(BaseModel):

    """Implementation of the 'DeviceId' model.

    TODO: type model description here.

    Attributes:
        id (string): TODO: type description here.
        kind (string): TODO: type description here.

    """

    def __init__(self, 
                 id = None,
                 kind = None):
        """Constructor for the DeviceId class"""
        
        # Initialize members of the class
        self.id = id
        self.kind = kind

        # Create a mapping from Model property names to API property names
        self.names = {
            "id" : "id",
            "kind" : "kind",
        }


    @classmethod
    def from_dictionary(cls, 
                        dictionary):
        """Creates an instance of this model from a dictionary
       
        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.
            
        Returns:
            object: An instance of this structure class.
            
        """
        if dictionary == None:
            return None
        else:
            # Extract variables from the dictionary
            id = dictionary.get("id")
            kind = dictionary.get("kind")
            # Return an object of this model
            return cls(id,
                       kind)
