# -*- coding: utf-8 -*-

"""
    thingspaceconnectivitymanagementapilib.models.device_usage_list_request
 
    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/05/2016
"""
from .device_id import DeviceId
from .base_model import BaseModel

class DeviceUsageListRequest(BaseModel):

    """Implementation of the 'DeviceUsageListRequest' model.

    TODO: type model description here.

    Attributes:
        device_id (DeviceId): TODO: type description here.
        earliest (string): TODO: type description here.
        latest (string): TODO: type description here.

    """

    def __init__(self, 
                 device_id = None,
                 earliest = None,
                 latest = None):
        """Constructor for the DeviceUsageListRequest class"""
        
        # Initialize members of the class
        self.device_id = device_id
        self.earliest = earliest
        self.latest = latest

        # Create a mapping from Model property names to API property names
        self.names = {
            "device_id" : "deviceId",
            "earliest" : "earliest",
            "latest" : "latest",
        }


    @classmethod
    def from_dictionary(cls, 
                        dictionary):
        """Creates an instance of this model from a dictionary
       
        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.
            
        Returns:
            object: An instance of this structure class.
            
        """
        if dictionary == None:
            return None
        else:
            # Extract variables from the dictionary
            device_id = DeviceId.from_dictionary(dictionary.get("deviceId")) if dictionary.get("deviceId") else None
            earliest = dictionary.get("earliest")
            latest = dictionary.get("latest")
            # Return an object of this model
            return cls(device_id,
                       earliest,
                       latest)
