# -*- coding: utf-8 -*-

"""
    thingspaceconnectivitymanagementapilib.models.device_provisioning_history_list_response
 
    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/05/2016
"""
from .provisioning_history import ProvisioningHistory
from .base_model import BaseModel

class DeviceProvisioningHistoryListResponse(BaseModel):

    """Implementation of the 'DeviceProvisioningHistoryListResponse' model.

    TODO: type model description here.

    Attributes:
        has_more_data (bool): TODO: type description here.
        provisioning_history (list of ProvisioningHistory): TODO: type
            description here.

    """

    def __init__(self, 
                 has_more_data = None,
                 provisioning_history = None):
        """Constructor for the DeviceProvisioningHistoryListResponse class"""
        
        # Initialize members of the class
        self.has_more_data = has_more_data
        self.provisioning_history = provisioning_history

        # Create a mapping from Model property names to API property names
        self.names = {
            "has_more_data" : "hasMoreData",
            "provisioning_history" : "provisioningHistory",
        }


    @classmethod
    def from_dictionary(cls, 
                        dictionary):
        """Creates an instance of this model from a dictionary
       
        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.
            
        Returns:
            object: An instance of this structure class.
            
        """
        if dictionary == None:
            return None
        else:
            # Extract variables from the dictionary
            has_more_data = dictionary.get("hasMoreData")
            provisioning_history = None
            if dictionary.get("provisioningHistory") != None:
                provisioning_history = list()
                for structure in dictionary.get("provisioningHistory"):
                    provisioning_history.append(ProvisioningHistory.from_dictionary(structure))
            # Return an object of this model
            return cls(has_more_data,
                       provisioning_history)
