# -*- coding: utf-8 -*-

"""
    thingspaceconnectivitymanagementapilib.models.group_list_response
 
    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/05/2016
"""
from .device_list import DeviceList
from .base_model import BaseModel

class GroupListResponse(BaseModel):

    """Implementation of the 'GroupListResponse' model.

    TODO: type model description here.

    Attributes:
        description (string): TODO: type description here.
        devices (list of DeviceList): TODO: type description here.
        has_more_data (bool): TODO: type description here.
        name (string): TODO: type description here.

    """

    def __init__(self, 
                 description = None,
                 devices = None,
                 has_more_data = None,
                 name = None):
        """Constructor for the GroupListResponse class"""
        
        # Initialize members of the class
        self.description = description
        self.devices = devices
        self.has_more_data = has_more_data
        self.name = name

        # Create a mapping from Model property names to API property names
        self.names = {
            "description" : "description",
            "devices" : "devices",
            "has_more_data" : "hasMoreData",
            "name" : "name",
        }


    @classmethod
    def from_dictionary(cls, 
                        dictionary):
        """Creates an instance of this model from a dictionary
       
        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.
            
        Returns:
            object: An instance of this structure class.
            
        """
        if dictionary == None:
            return None
        else:
            # Extract variables from the dictionary
            description = dictionary.get("description")
            devices = None
            if dictionary.get("devices") != None:
                devices = list()
                for structure in dictionary.get("devices"):
                    devices.append(DeviceList.from_dictionary(structure))
            has_more_data = dictionary.get("hasMoreData")
            name = dictionary.get("name")
            # Return an object of this model
            return cls(description,
                       devices,
                       has_more_data,
                       name)
