# -*- coding: utf-8 -*-

"""
    thingspaceconnectivitymanagementapilib.models.kv_pair
 
    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/05/2016
"""
from .base_model import BaseModel

class KvPair(BaseModel):

    """Implementation of the 'KvPair' model.

    TODO: type model description here.

    Attributes:
        key (string): TODO: type description here.
        value (string): TODO: type description here.

    """

    def __init__(self, 
                 key = None,
                 value = None):
        """Constructor for the KvPair class"""
        
        # Initialize members of the class
        self.key = key
        self.value = value

        # Create a mapping from Model property names to API property names
        self.names = {
            "key" : "key",
            "value" : "value",
        }


    @classmethod
    def from_dictionary(cls, 
                        dictionary):
        """Creates an instance of this model from a dictionary
       
        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.
            
        Returns:
            object: An instance of this structure class.
            
        """
        if dictionary == None:
            return None
        else:
            # Extract variables from the dictionary
            key = dictionary.get("key")
            value = dictionary.get("value")
            # Return an object of this model
            return cls(key,
                       value)
