# -*- coding: utf-8 -*-

"""
    thingspaceconnectivitymanagementapilib.models.lead_information_response
 
    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/05/2016
"""
from .lead_response import LeadResponse
from .base_model import BaseModel

class LeadInformationResponse(BaseModel):

    """Implementation of the 'LeadInformationResponse' model.

    TODO: type model description here.

    Attributes:
        has_more_data (bool): TODO: type description here.
        leads (list of LeadResponse): TODO: type description here.

    """

    def __init__(self, 
                 has_more_data = None,
                 leads = None):
        """Constructor for the LeadInformationResponse class"""
        
        # Initialize members of the class
        self.has_more_data = has_more_data
        self.leads = leads

        # Create a mapping from Model property names to API property names
        self.names = {
            "has_more_data" : "hasMoreData",
            "leads" : "leads",
        }


    @classmethod
    def from_dictionary(cls, 
                        dictionary):
        """Creates an instance of this model from a dictionary
       
        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.
            
        Returns:
            object: An instance of this structure class.
            
        """
        if dictionary == None:
            return None
        else:
            # Extract variables from the dictionary
            has_more_data = dictionary.get("hasMoreData")
            leads = None
            if dictionary.get("leads") != None:
                leads = list()
                for structure in dictionary.get("leads"):
                    leads.append(LeadResponse.from_dictionary(structure))
            # Return an object of this model
            return cls(has_more_data,
                       leads)
