# -*- coding: utf-8 -*-

"""
    thingspaceconnectivitymanagementapilib.models.lead_response
 
    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/05/2016
"""
from .address import Address
from .base_model import BaseModel

class LeadResponse(BaseModel):

    """Implementation of the 'LeadResponse' model.

    TODO: type model description here.

    Attributes:
        address (Address): TODO: type description here.
        lead_id (string): TODO: type description here.
        lead_state (string): TODO: type description here.

    """

    def __init__(self, 
                 address = None,
                 lead_id = None,
                 lead_state = None):
        """Constructor for the LeadResponse class"""
        
        # Initialize members of the class
        self.address = address
        self.lead_id = lead_id
        self.lead_state = lead_state

        # Create a mapping from Model property names to API property names
        self.names = {
            "address" : "address",
            "lead_id" : "leadId",
            "lead_state" : "leadState",
        }


    @classmethod
    def from_dictionary(cls, 
                        dictionary):
        """Creates an instance of this model from a dictionary
       
        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.
            
        Returns:
            object: An instance of this structure class.
            
        """
        if dictionary == None:
            return None
        else:
            # Extract variables from the dictionary
            address = Address.from_dictionary(dictionary.get("address")) if dictionary.get("address") else None
            lead_id = dictionary.get("leadId")
            lead_state = dictionary.get("leadState")
            # Return an object of this model
            return cls(address,
                       lead_id,
                       lead_state)
