# -*- coding: utf-8 -*-

"""
    thingspaceconnectivitymanagementapilib.models.log_in_response
 
    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/05/2016
"""
from .base_model import BaseModel

class LogInResponse(BaseModel):

    """Implementation of the 'LogInResponse' model.

    TODO: type model description here.

    Attributes:
        session_token (string): TODO: type description here.

    """

    def __init__(self, 
                 session_token = None):
        """Constructor for the LogInResponse class"""
        
        # Initialize members of the class
        self.session_token = session_token

        # Create a mapping from Model property names to API property names
        self.names = {
            "session_token" : "sessionToken",
        }


    @classmethod
    def from_dictionary(cls, 
                        dictionary):
        """Creates an instance of this model from a dictionary
       
        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.
            
        Returns:
            object: An instance of this structure class.
            
        """
        if dictionary == None:
            return None
        else:
            # Extract variables from the dictionary
            session_token = dictionary.get("sessionToken")
            # Return an object of this model
            return cls(session_token)
