# -*- coding: utf-8 -*-

"""
    thingspaceconnectivitymanagementapilib.models.log_in_request
 
    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/05/2016
"""
from .base_model import BaseModel

class LogInRequest(BaseModel):

    """Implementation of the 'LogInRequest' model.

    TODO: type model description here.

    Attributes:
        username (string): TODO: type description here.
        password (string): TODO: type description here.

    """

    def __init__(self, 
                 username = None,
                 password = None):
        """Constructor for the LogInRequest class"""
        
        # Initialize members of the class
        self.username = username
        self.password = password

        # Create a mapping from Model property names to API property names
        self.names = {
            "username" : "username",
            "password" : "password",
        }


    @classmethod
    def from_dictionary(cls, 
                        dictionary):
        """Creates an instance of this model from a dictionary
       
        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.
            
        Returns:
            object: An instance of this structure class.
            
        """
        if dictionary == None:
            return None
        else:
            # Extract variables from the dictionary
            username = dictionary.get("username")
            password = dictionary.get("password")
            # Return an object of this model
            return cls(username,
                       password)
