# -*- coding: utf-8 -*-

"""
    thingspaceconnectivitymanagementapilib.models.place_of_use
 
    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/05/2016
"""
from .address import Address
from .customer_name import CustomerName
from .base_model import BaseModel

class PlaceOfUse(BaseModel):

    """Implementation of the 'PlaceOfUse' model.

    TODO: type model description here.

    Attributes:
        address (Address): TODO: type description here.
        customer_name (CustomerName): TODO: type description here.

    """

    def __init__(self, 
                 address = None,
                 customer_name = None):
        """Constructor for the PlaceOfUse class"""
        
        # Initialize members of the class
        self.address = address
        self.customer_name = customer_name

        # Create a mapping from Model property names to API property names
        self.names = {
            "address" : "address",
            "customer_name" : "customerName",
        }


    @classmethod
    def from_dictionary(cls, 
                        dictionary):
        """Creates an instance of this model from a dictionary
       
        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.
            
        Returns:
            object: An instance of this structure class.
            
        """
        if dictionary == None:
            return None
        else:
            # Extract variables from the dictionary
            address = Address.from_dictionary(dictionary.get("address")) if dictionary.get("address") else None
            customer_name = CustomerName.from_dictionary(dictionary.get("customerName")) if dictionary.get("customerName") else None
            # Return an object of this model
            return cls(address,
                       customer_name)
