# -*- coding: utf-8 -*-

"""
    thingspaceconnectivitymanagementapilib.models.register_callback_request
 
    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/05/2016
"""
from .base_model import BaseModel

class RegisterCallbackRequest(BaseModel):

    """Implementation of the 'RegisterCallbackRequest' model.

    TODO: type model description here.

    Attributes:
        name (string): TODO: type description here.
        url (string): TODO: type description here.
        username (string): TODO: type description here.
        password (string): TODO: type description here.

    """

    def __init__(self, 
                 name = None,
                 url = None,
                 username = None,
                 password = None):
        """Constructor for the RegisterCallbackRequest class"""
        
        # Initialize members of the class
        self.name = name
        self.url = url
        self.username = username
        self.password = password

        # Create a mapping from Model property names to API property names
        self.names = {
            "name" : "name",
            "url" : "url",
            "username" : "username",
            "password" : "password",
        }


    @classmethod
    def from_dictionary(cls, 
                        dictionary):
        """Creates an instance of this model from a dictionary
       
        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.
            
        Returns:
            object: An instance of this structure class.
            
        """
        if dictionary == None:
            return None
        else:
            # Extract variables from the dictionary
            name = dictionary.get("name")
            url = dictionary.get("url")
            username = dictionary.get("username")
            password = dictionary.get("password")
            # Return an object of this model
            return cls(name,
                       url,
                       username,
                       password)
