# -*- coding: utf-8 -*-

"""
    thingspaceconnectivitymanagementapilib.models.request_response
 
    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/05/2016
"""
from .base_model import BaseModel

class RequestResponse(BaseModel):

    """Implementation of the 'RequestResponse' model.

    TODO: type model description here.

    Attributes:
        request_id (string): TODO: type description here.

    """

    def __init__(self, 
                 request_id = None):
        """Constructor for the RequestResponse class"""
        
        # Initialize members of the class
        self.request_id = request_id

        # Create a mapping from Model property names to API property names
        self.names = {
            "request_id" : "requestId",
        }


    @classmethod
    def from_dictionary(cls, 
                        dictionary):
        """Creates an instance of this model from a dictionary
       
        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.
            
        Returns:
            object: An instance of this structure class.
            
        """
        if dictionary == None:
            return None
        else:
            # Extract variables from the dictionary
            request_id = dictionary.get("requestId")
            # Return an object of this model
            return cls(request_id)
