# -*- coding: utf-8 -*-

"""
    thingspaceconnectivitymanagementapilib.models.rest_success_response
 
    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/05/2016
"""
from .base_model import BaseModel

class RestSuccessResponse(BaseModel):

    """Implementation of the 'RestSuccessResponse' model.

    TODO: type model description here.

    Attributes:
        success (bool): TODO: type description here.

    """

    def __init__(self, 
                 success = None):
        """Constructor for the RestSuccessResponse class"""
        
        # Initialize members of the class
        self.success = success

        # Create a mapping from Model property names to API property names
        self.names = {
            "success" : "success",
        }


    @classmethod
    def from_dictionary(cls, 
                        dictionary):
        """Creates an instance of this model from a dictionary
       
        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.
            
        Returns:
            object: An instance of this structure class.
            
        """
        if dictionary == None:
            return None
        else:
            # Extract variables from the dictionary
            success = dictionary.get("success")
            # Return an object of this model
            return cls(success)
