# -*- coding: utf-8 -*-

"""
    thingspaceconnectivitymanagementapilib.models.service_plan_response
 
    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/05/2016
"""
from .kv_pair import KvPair
from .base_model import BaseModel

class ServicePlanResponse(BaseModel):

    """Implementation of the 'ServicePlanResponse' model.

    TODO: type model description here.

    Attributes:
        carrier_service_plan_code (string): TODO: type description here.
        code (string): TODO: type description here.
        extended_attributes (list of KvPair): TODO: type description here.
        name (string): TODO: type description here.
        size_kb (long|int): TODO: type description here.

    """

    def __init__(self, 
                 carrier_service_plan_code = None,
                 code = None,
                 extended_attributes = None,
                 name = None,
                 size_kb = None):
        """Constructor for the ServicePlanResponse class"""
        
        # Initialize members of the class
        self.carrier_service_plan_code = carrier_service_plan_code
        self.code = code
        self.extended_attributes = extended_attributes
        self.name = name
        self.size_kb = size_kb

        # Create a mapping from Model property names to API property names
        self.names = {
            "carrier_service_plan_code" : "carrierServicePlanCode",
            "code" : "code",
            "extended_attributes" : "extendedAttributes",
            "name" : "name",
            "size_kb" : "sizeKb",
        }


    @classmethod
    def from_dictionary(cls, 
                        dictionary):
        """Creates an instance of this model from a dictionary
       
        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.
            
        Returns:
            object: An instance of this structure class.
            
        """
        if dictionary == None:
            return None
        else:
            # Extract variables from the dictionary
            carrier_service_plan_code = dictionary.get("carrierServicePlanCode")
            code = dictionary.get("code")
            extended_attributes = None
            if dictionary.get("extendedAttributes") != None:
                extended_attributes = list()
                for structure in dictionary.get("extendedAttributes"):
                    extended_attributes.append(KvPair.from_dictionary(structure))
            name = dictionary.get("name")
            size_kb = dictionary.get("sizeKb")
            # Return an object of this model
            return cls(carrier_service_plan_code,
                       code,
                       extended_attributes,
                       name,
                       size_kb)
