# -*- coding: utf-8 -*-

"""
    thingspaceconnectivitymanagementapilib.models.sms_messages_response
 
    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/05/2016
"""
from .sms_message import SmsMessage
from .base_model import BaseModel

class SmsMessagesResponse(BaseModel):

    """Implementation of the 'SmsMessagesResponse' model.

    TODO: type model description here.

    Attributes:
        has_more_data (bool): TODO: type description here.
        messages (list of SmsMessage): TODO: type description here.

    """

    def __init__(self, 
                 has_more_data = None,
                 messages = None):
        """Constructor for the SmsMessagesResponse class"""
        
        # Initialize members of the class
        self.has_more_data = has_more_data
        self.messages = messages

        # Create a mapping from Model property names to API property names
        self.names = {
            "has_more_data" : "hasMoreData",
            "messages" : "messages",
        }


    @classmethod
    def from_dictionary(cls, 
                        dictionary):
        """Creates an instance of this model from a dictionary
       
        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.
            
        Returns:
            object: An instance of this structure class.
            
        """
        if dictionary == None:
            return None
        else:
            # Extract variables from the dictionary
            has_more_data = dictionary.get("hasMoreData")
            messages = None
            if dictionary.get("messages") != None:
                messages = list()
                for structure in dictionary.get("messages"):
                    messages.append(SmsMessage.from_dictionary(structure))
            # Return an object of this model
            return cls(has_more_data,
                       messages)
