# -*- coding: utf-8 -*-

"""
   thingspaceconnectivitymanagementapilib.configuration

   This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/05/2016
"""

class Configuration(object):
    # The base Uri for API calls
    BASE_URI = 'https://example.com/api/m2m/v1'

    api_key = '';


