# -*- coding: utf-8 -*-

"""
    thingspaceconnectivitymanagementapilib.thing_space_connectivity_management_api_client

    This file was automatically generated by APIMATIC BETA v2.0 on 10/05/2016
"""

from .http import *
from .models import *
from .exceptions import *
from .decorators import *
from .controllers import *

class ThingSpaceConnectivityManagementAPIClient(object):

    @lazy_property
    def sms(self):
        return SmsController()

    @lazy_property
    def session(self):
        return SessionController()

    @lazy_property
    def plans(self):
        return PlansController()

    @lazy_property
    def leads(self):
        return LeadsController()

    @lazy_property
    def groups(self):
        return GroupsController()

    @lazy_property
    def devices(self):
        return DevicesController()

    @lazy_property
    def callbacks(self):
        return CallbacksController()



